[package]
name = "phil"
description = "A CLI orchestration tool for monger"
version = "0.1.0"
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
edition = "2018"
readme = "../README.md"

[dependencies]
clap = "2.33.0"
percent-encoding = "2.1.0"
thiserror = "1.0.11"
structopt = "0.3.16"
self_update = "0.19.0"
anyhow = "1.0.32"

[dependencies.mongodb]
git = "https://github.com/mongodb/mongo-rust-driver"
rev = "65adb24f95d1108600985c6f0b0055db1253ebd7"
default-features = false
features = ["sync"]

[dependencies.uuid]
version = "0.8.1"
features = ["v4"]

[dependencies.phil-core]
path = "../phil-core"
