[package]
name = "phil"
description = "A CLI orchestration tool for monger"
version = "0.1.0"
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
err-derive = "0.2.0"
mongodb = "0.9.0"
percent-encoding = "2.1.0"

[dependencies.uuid]
version = "0.8.1"
features = ["v4"]

[dependencies.phil-core]
path = "../phil-core"
