[package]
name = "phil-core"
version = "0.2.0"
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
edition = "2018"
readme = "../README.md"

[dependencies]
monger-core = "0.13.0"
percent-encoding = "2.1.0"
typed-builder = "0.7.0"
thiserror = "1.0.11"

[dependencies.mongodb]
git = "https://github.com/mongodb/mongo-rust-driver"
rev = "65adb24f95d1108600985c6f0b0055db1253ebd7"
default-features = false
features = ["sync"]

[dependencies.serde]
version = "1.0.115"
features = ["derive"]

[dev-dependencies]
tempdir = "0.3.7"

[dev-dependencies.uuid]
version = "0.8.1"
features = [ "v4" ]
