[package]
name = "phil-core"
version = "0.1.0"
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
edition = "2018"
readme = "../README.md"

[dependencies]
monger-core = "0.13.0"
mongodb = { version = "1.1.0", default-features = false, features = ["sync"] }
percent-encoding = "2.1.0"
typed-builder = "0.7.0"
thiserror = "1.0.11"

[dependencies.serde]
version = "1.0.115"
features = ["derive"]

[dev-dependencies]
tempdir = "0.3.7"

[dev-dependencies.uuid]
version = "0.8.1"
features = [ "v4" ]
