[package]
name = "phil-core"
version = "0.1.0"
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
edition = "2018"

[dependencies]
err-derive = "0.2.0"
typed-builder = "0.3.0"
percent-encoding = "2.1.0"
monger-core = "0.9.0"

[dependencies.mongodb]
#path = "/home/saghm/code/mongo/rust/driver"
git = "file:///home/saghm/code/mongo/rust/driver"
branch = "foo"

[dependencies.serde]
version = "1.0.101"
features = ["derive"]

[dev-dependencies]
tempdir = "0.3.7"

[dev-dependencies.uuid]
version = "0.7.4"
features = [ "v4" ]
